### ISSUE TITLE
load_dataset

### ISSUE THREAD

**Issue by ghost** [xcompact3d/Py4Incompact3D#21]
def load_dataset(input_file, t):
    postprocess = Postprocess(input_file)
    mesh = postprocess.mesh
    yp = mesh.get_grid()[1]

    postprocess.load(time=[t])

    return postprocess.fields["umean"].data[t], \
           postprocess.fields["vmean"].data[t], \
           postprocess.fields["wmean"].data[t], \
           postprocess.fields["uumean"].data[t], \
           postprocess.fields["vvmean"].data[t], \
           postprocess.fields["wwmean"].data[t], \
           mesh
           
           here, uvmean, uwmean, vwmean can not load. please solve the problem. Thanks in advance.

**Comment by pbartholomew08** [comment]
Hi @hamedsedighi563 I will need more information than that, what is the error? Which problem are you running, what is your input file? Does your dataset have `uvmean` etc?

**Comment by ghost** [comment]
> Hi @hamedsedighi563 I will need more information than that, what is the error? Which problem are you running, what is your input file? Does your dataset have `uvmean` etc?

Hi, Thank you for your reply. 
postprocess.fields["uvmean"].data[t], \KeyError: 'uvmean', this is the error, 
just consider running Channel-Flow case with default input_DNS_Re180_LR_explicittime.i3d file, yes, in database uvmean exist, and this error happen regardless of changing in input file.

**Comment by hamedsedighi563** [comment]
Hi, Thank you for your reply.
postprocess.fields["uvmean"].data[t], \KeyError: 'uvmean', this is the error,
just consider running Channel-Flow case with default input_DNS_Re180_LR_explicittime.i3d file, yes, in database uvmean exist, and this error happen regardless of changing in input file.
